version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=info
    secrets:
      - mongodb_uri
      - tts_url
      - ollama_api_key
    depends_on:
      - mongo
      - tts
    networks:
      - resilient
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - resilient
  tts:
    build:
      context: ../tts
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - resilient
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    secrets:
      - mongo_root_password
      - mongo_encryption_key
    networks:
      - resilient
secrets:
  mongodb_uri:
    file: ./secrets/mongodb_uri.txt
  tts_url:
    file: ./secrets/tts_url.txt
  ollama_api_key:
    file: ./secrets/ollama_api_key.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  mongo_encryption_key:
    file: ./secrets/mongo_encryption_key.txt
networks:
  resilient:
    driver: bridge 