apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilient-ai-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resilient-ai-backend
  template:
    metadata:
      labels:
        app: resilient-ai-backend
    spec:
      containers:
      - name: backend
        image: resilient-ai-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017"
        - name: TTS_URL
          value: "http://tts:5002"
        - name: RUST_LOG
          value: info
        - name: OLLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: ollama-secrets
              key: api-key
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: resilient-ai-backend
spec:
  selector:
    app: resilient-ai-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: ollama-secrets
stringData:
  api-key: "your-ollama-api-key-here"
