apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilient-ai-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resilient-ai-frontend
  template:
    metadata:
      labels:
        app: resilient-ai-frontend
    spec:
      containers:
      - name: frontend
        image: resilient-ai-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://backend:3001"
        - name: NEXT_PUBLIC_TTS_URL
          value: "http://tts:5002"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: resilient-ai-frontend
spec:
  selector:
    app: resilient-ai-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
